name: 'Amazon ECS "Run Task" Action for GitHub Actions'
description: 'Registers an Amazon ECS task definition, and runs it on the give ECS cluster'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The name of ECS task definition'
    required: true
  cluster:
    description: "The name of the ECS cluster."
    required: true
  count:
    description: "The count of tasks to run. Will default to 1"
    required: true
  started-by:
    description: "The value of the task started-by"
    required: false
  wait-for-finish:
    description: "Whether to wait for tasks to reach stopped state. Will default to not waiting"
    required: false
  wait-for-minutes:
    description: 'How long to wait for the task reach stopped state, in minutes (default: 30 minutes, max: 6 hours).'
    required: false
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
  task-arn:
    description: 'The ARN of the ECS task'
runs:
  using: 'node12'
  main: 'dist/index.js'
